# This pipeline expects one VCF.gz file per chromosome (e.g. chr1.vcf.gz, chr2.vcf.gz, etc.)
# and a genetic map file in the SHAPEIT format.
data_dir: "example/"
# Either LD or IBD
method: "ld"
# Configuration for the LD method
maf_threshold: 0.25
pseudo_diploid: false
nb_points: 1e6
